---
title: Peter Hironaka
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: true
  producer:
    title: Producer
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: peterhironaka@mac.com
description: Front End Developer based in Venice, CA.
asset: "/uploads/DSCF6211.JPG"
baseurl: 
url: http://peterhironaka.com
twitter_username: peterhironaka
github_username: phironaka
instagram_username: peterhironaka
codepen_username: peterhironaka
gems:
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
permalink: pretty
wnw_username: 8975
twitter:
  username: peterhironaka
