---
title: Peter Hironaka
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  producer:
    title: Producer
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: peterhironaka@mac.com
description: Web Developer based in Venice, CA.
asset: "/uploads/space-pic.jpg"
baseurl: 
url: http://peterhironaka.com
twitter_username: peterhironaka
github_username: phironaka
instagram_username: peterhironaka
codepen_username: peterhironaka
gems:
- jekyll-seo-tag
- jekyll/tagging
markdown: kramdown
permalink: pretty
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tags
wnw_username: 8975
twitter:
  username: peterhironaka
