---
title: Peter Hironaka
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: your-email@domain.com
description: |
  Peter Hironaka is a Digital Producer & Front-End Developer living by the beach in Los Angeles,CA.
baseurl:
url: http://yourdomain.com
twitter_username: peterhironaka
github_username: peterhironaka
markdown: kramdown
permalink: pretty
