---
title: Peter Hironaka
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  production-credits:
    title: Production Credits
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: your-email@domain.com
description: "Hello \U0001F44B\U0001F3FC, my name is Peter Hironaka.\n\n\na Front-End
  Developer based in Venice, California. When I’m not in the ocean attempting to surf,
  I can be found  reading a book or refactoring old bits of Open Source code. If you
  have a project you’re interested in collaborating on, feel free to drop me a line
  on email.\n\nOtherwise, I can be found on the usual: Twitter, Facebook, Instagram,
  Snapchat.\n\nHere is my Resumé.\n\nBoom."
asset: "/uploads/DSCF6211.JPG"
baseurl: 
url: http://yourdomain.com
twitter_username: peterhironaka
github_username: phironaka
instagram_username: peterhironaka
codepen_username: peterhironaka
markdown: kramdown
permalink: pretty
