---
title: Peter Hironaka
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  producer:
    title: Producer
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: your-email@domain.com
description: Front End Developer based in Venice, CA.
asset: "/uploads/DSCF6211.JPG"
baseurl: 
url: http://yourdomain.com
twitter_username: peterhironaka
github_username: phironaka
instagram_username: peterhironaka
codepen_username: peterhironaka
markdown: kramdown
permalink: pretty
wnw_username: 8975
